---
- name: "create the gogs problem"
  hosts: "app"
  become: yes
  tasks:
    - name: "mange gogs custom ini file"
      lineinfile:
        path: "/srv/gogs/custom/conf/app.ini"
        regexp: "^HOST = db.interview.vm:3306$"
        line: "HOST = db.interview.vm:3308"
        state: "present"
      notify: "restart gogs"

  handlers:
    - name: "restart gogs"
      service:
        name: "gogs"
        state: "restarted"
      failed_when: false

- include: "copy_task_to_desktop.yml"
