---
filebeat.modules:
  - module: system
    syslog:
      enabled: true
filebeat.prospectors:
  - input_type: log
    paths:
      - /var/log/*.log
output.logstash:
  hosts:
    - 192.168.0.9:5044
logging.level: error
