---
- name: "handle missing python 2.7"
  hosts: app
  gather_facts: no
  tasks:
    - raw: sudo apt-get update -qq && sudo apt-get install -qq python2.7
    - raw: sudo ln -sf /usr/bin/python2.7 /usr/bin/python

- name: "install localized filebeat"
  hosts: app
  become: yes
  roles:
    - filebeat

- name: "install goss and gogs"
  hosts: app
  become: yes
  vars:
    gogs_database_name: gogs
    gogs_database_user: gogs
    gogs_database_password: gogs
    gogs_domain: git.example.com
    gogs_database_uri: db.interview.vm:3306
  roles:
    - install_goss
    - alvaroaleman.gogs

